services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - san_network

  php:
    image: php:8.2-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - san_network

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - san_network

  redis:
    image: redis:latest
    container_name: redis01
    restart: always
    ports:
      - "6379:6379"
    networks:
      - san_network

networks:
  san_network:
    driver: bridge

volumes:
  postgres_data:
